/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cellfixx.solutions;

import javax.swing.JTable;

/**
 *
 * @author Mohammed Siddiq
 */
public class Cellfixx extends javax.swing.JFrame {

    /**
     * Creates new form Cellfixx
     */
    public Cellfixx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JPanel();
        jpsignup = new javax.swing.JPanel();
        jlans = new javax.swing.JLabel();
        confirm_pass = new javax.swing.JLabel();
        tfuname = new javax.swing.JTextField();
        tfgymname = new javax.swing.JTextField();
        bregister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlgymname = new javax.swing.JLabel();
        pfconf = new javax.swing.JPasswordField();
        security_question = new javax.swing.JComboBox();
        tfanswer = new javax.swing.JTextField();
        jlconfpass = new javax.swing.JLabel();
        jluname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlquest = new javax.swing.JLabel();
        pf = new javax.swing.JPasswordField();
        jlpass = new javax.swing.JLabel();
        jplogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tflusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blogin = new javax.swing.JButton();
        pfl = new javax.swing.JPasswordField();
        jpall = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jpmembers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_mymember = new javax.swing.JTable();
        tfdamt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdcontact = new javax.swing.JTextField();
        tfdname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfddoj = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jppayinfo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_mymember1 = new javax.swing.JTable();
        tfdamt1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfdcontact1 = new javax.swing.JTextField();
        tfdname1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfddoj1 = new javax.swing.JTextField();
        bamountpaid = new javax.swing.JButton();
        jpstats = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        stf_males = new javax.swing.JTextField();
        stf_females = new javax.swing.JTextField();
        stf_amountrcv = new javax.swing.JTextField();
        stf_amountbal = new javax.swing.JTextField();
        jpsettings = new javax.swing.JPanel();
        confirm_pass1 = new javax.swing.JLabel();
        jpaddmember = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tfmname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfmphone = new javax.swing.JTextField();
        tfmptamt = new javax.swing.JTextField();
        jlpdate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        searchfield = new javax.swing.JTextField();
        search_label = new javax.swing.JLabel();
        jpforgotpassword = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ftf_secq = new javax.swing.JTextField();
        ftf_seca = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        fbresetpass = new javax.swing.JButton();
        flabel_newpass = new javax.swing.JLabel();
        fpf_newpass = new javax.swing.JPasswordField();
        fpf_confpass = new javax.swing.JPasswordField();
        flabel_confpass = new javax.swing.JLabel();
        fbsetpass = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        conf_pass1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp1.setLayout(new java.awt.CardLayout());

        jpsignup.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign-Up", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 204, 255))); // NOI18N

        jlans.setText("Answer");

        tfuname.setText("Name");
        tfuname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfunameMouseClicked(evt);
            }
        });
        tfuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfunameActionPerformed(evt);
            }
        });

        tfgymname.setText("Cellfixx ");
        tfgymname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfgymnameMouseClicked(evt);
            }
        });
        tfgymname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgymnameActionPerformed(evt);
            }
        });
        tfgymname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfgymnameKeyReleased(evt);
            }
        });

        bregister.setText("Register");
        bregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregisterActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*at least 8 characters");

        jlgymname.setText("Service Center Name");

        pfconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfconfActionPerformed(evt);
            }
        });
        pfconf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfconfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfconfKeyTyped(evt);
            }
        });

        security_question.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Your First School Name?", "Which phone number do you remember most from your childhood?", "What was the name of the hospital where you were born?", "Which month is your best friends birthday?", "which is your dream destination?", "what is the name of your first crush?", " " }));

        tfanswer.setText("Your Answer");
        tfanswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfanswerMouseClicked(evt);
            }
        });
        tfanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfanswerActionPerformed(evt);
            }
        });
        tfanswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfanswerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfanswerKeyReleased(evt);
            }
        });

        jlconfpass.setText("Confirm Your Password");

        jluname.setText("User Name");

        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("* Remember your selection and the answer for a password reset.");

        jlquest.setText("Security Question");

        pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfActionPerformed(evt);
            }
        });

        jlpass.setText("Password");

        javax.swing.GroupLayout jpsignupLayout = new javax.swing.GroupLayout(jpsignup);
        jpsignup.setLayout(jpsignupLayout);
        jpsignupLayout.setHorizontalGroup(
            jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsignupLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlconfpass)
                    .addComponent(jlquest)
                    .addComponent(jlans)
                    .addComponent(jlpass)
                    .addComponent(jluname)
                    .addComponent(jlgymname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpsignupLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpsignupLayout.createSequentialGroup()
                        .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(security_question, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addGroup(jpsignupLayout.createSequentialGroup()
                                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfgymname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfuname)
                                    .addComponent(pf)
                                    .addComponent(pfconf))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jpsignupLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(confirm_pass))))
                            .addComponent(tfanswer, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(484, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bregister)
                .addGap(437, 437, 437))
        );
        jpsignupLayout.setVerticalGroup(
            jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsignupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlgymname)
                    .addComponent(tfgymname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jluname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlpass)
                    .addComponent(pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlconfpass)
                    .addComponent(pfconf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm_pass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(security_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlquest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jpsignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlans)
                    .addComponent(tfanswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 73, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bregister, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jp1.add(jpsignup, "card2");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log in", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel1.setText("User Name");

        tflusername.setText("Username");
        tflusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tflusernameMouseClicked(evt);
            }
        });
        tflusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflusernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Forgot Password ?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel2.setText("Password");

        blogin.setText("Log in");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });

        pfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pflActionPerformed(evt);
            }
        });
        pfl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pflKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tflusername)
                            .addComponent(pfl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blogin))
                        .addGap(40, 40, 40)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tflusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pfl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(blogin)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jploginLayout = new javax.swing.GroupLayout(jplogin);
        jplogin.setLayout(jploginLayout);
        jploginLayout.setHorizontalGroup(
            jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jploginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jploginLayout.setVerticalGroup(
            jploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jploginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp1.add(jplogin, "card4");

        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });

        table_mymember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_mymember.getTableHeader().setReorderingAllowed(false);
        table_mymember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mymemberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table_mymemberMouseEntered(evt);
            }
        });
        table_mymember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_mymemberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_mymemberKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_mymember);

        tfdamt.setEditable(false);
        tfdamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdamtActionPerformed(evt);
            }
        });

        jLabel10.setText("Due Amount");

        jLabel6.setText("Date ");

        tfdcontact.setEditable(false);
        tfdcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdcontactActionPerformed(evt);
            }
        });

        tfdname.setEditable(false);
        tfdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdnameActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel5.setText("Contact Number");

        tfddoj.setEditable(false);
        tfddoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfddojActionPerformed(evt);
            }
        });

        jButton6.setText("Delete Entry");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Update/Modification");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpmembersLayout = new javax.swing.GroupLayout(jpmembers);
        jpmembers.setLayout(jpmembersLayout);
        jpmembersLayout.setHorizontalGroup(
            jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmembersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfdname)
                    .addComponent(tfddoj)
                    .addComponent(tfdcontact)
                    .addComponent(tfdamt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpmembersLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpmembersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(44, 44, 44)
                .addComponent(jButton6)
                .addGap(52, 52, 52))
        );
        jpmembersLayout.setVerticalGroup(
            jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpmembersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfddoj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(jpmembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfdamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tab.addTab("My Services", jpmembers);

        table_mymember1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl.no", "Name", "DOJ", "Contact Number", "Due amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_mymember1.getTableHeader().setReorderingAllowed(false);
        table_mymember1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mymember1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table_mymember1MouseEntered(evt);
            }
        });
        table_mymember1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_mymember1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_mymember1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(table_mymember1);

        tfdamt1.setEditable(false);
        tfdamt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdamt1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Due Amount");

        jLabel30.setText("Due Date");

        tfdcontact1.setEditable(false);
        tfdcontact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdcontact1ActionPerformed(evt);
            }
        });

        tfdname1.setEditable(false);
        tfdname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdname1ActionPerformed(evt);
            }
        });

        jLabel31.setText("Name");

        jLabel32.setText("Contact Number");

        tfddoj1.setEditable(false);
        tfddoj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfddoj1ActionPerformed(evt);
            }
        });

        bamountpaid.setText("Amount Paid");
        bamountpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bamountpaidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jppayinfoLayout = new javax.swing.GroupLayout(jppayinfo);
        jppayinfo.setLayout(jppayinfoLayout);
        jppayinfoLayout.setHorizontalGroup(
            jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppayinfoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jppayinfoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(167, Short.MAX_VALUE))
                    .addGroup(jppayinfoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addGap(116, 116, 116)
                        .addGroup(jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdcontact1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfddoj1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfdname1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfdamt1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(74, 74, 74)
                        .addComponent(bamountpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        jppayinfoLayout.setVerticalGroup(
            jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppayinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jppayinfoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(tfdname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdcontact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(30, 30, 30)
                        .addGroup(jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfddoj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jppayinfoLayout.createSequentialGroup()
                        .addComponent(bamountpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jppayinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfdamt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        tab.addTab("Expected Payements", jppayinfo);

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("Total services Done.                                                       ");

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("Services Pending.");

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("Amount Recieved  this month                         ");

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 51));
        jLabel33.setText("Amount yet to recieve (Balance:till the end of this month)");

        stf_males.setEditable(false);

        stf_females.setEditable(false);

        stf_amountrcv.setEditable(false);
        stf_amountrcv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stf_amountrcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stf_amountrcvActionPerformed(evt);
            }
        });

        stf_amountbal.setEditable(false);
        stf_amountbal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stf_amountbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stf_amountbalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpstatsLayout = new javax.swing.GroupLayout(jpstats);
        jpstats.setLayout(jpstatsLayout);
        jpstatsLayout.setHorizontalGroup(
            jpstatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpstatsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpstatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpstatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stf_amountrcv)
                    .addComponent(stf_females)
                    .addComponent(stf_males, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stf_amountbal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpstatsLayout.setVerticalGroup(
            jpstatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpstatsLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jpstatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(stf_males, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jpstatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(stf_females, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jpstatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(stf_amountrcv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jpstatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stf_amountbal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        tab.addTab("Stats.", jpstats);

        javax.swing.GroupLayout jpsettingsLayout = new javax.swing.GroupLayout(jpsettings);
        jpsettings.setLayout(jpsettingsLayout);
        jpsettingsLayout.setHorizontalGroup(
            jpsettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsettingsLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(confirm_pass1)
                .addContainerGap(662, Short.MAX_VALUE))
        );
        jpsettingsLayout.setVerticalGroup(
            jpsettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsettingsLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(confirm_pass1)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        tab.addTab("Account Settings", jpsettings);

        jLabel12.setText("Name *");

        tfmname.setText("Full Name");
        tfmname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfmnameMouseClicked(evt);
            }
        });
        tfmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmnameActionPerformed(evt);
            }
        });

        jLabel13.setText("Contact Number");

        tfmphone.setText("Number");
        tfmphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfmphoneMouseClicked(evt);
            }
        });
        tfmphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmphoneActionPerformed(evt);
            }
        });
        tfmphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfmphoneKeyTyped(evt);
            }
        });

        tfmptamt.setText("Amt");
        tfmptamt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfmptamtMouseClicked(evt);
            }
        });
        tfmptamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmptamtActionPerformed(evt);
            }
        });
        tfmptamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfmptamtKeyTyped(evt);
            }
        });

        jlpdate.setDateFormatString("yyy-MM-dd");

        jLabel9.setText("Service Amount");

        jButton2.setText("Add Service");

        jLabel14.setText("Expected Delivery Date");

        javax.swing.GroupLayout jpaddmemberLayout = new javax.swing.GroupLayout(jpaddmember);
        jpaddmember.setLayout(jpaddmemberLayout);
        jpaddmemberLayout.setHorizontalGroup(
            jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaddmemberLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(39, 39, 39)
                .addGroup(jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfmname, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jlpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfmphone)
                    .addComponent(tfmptamt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpaddmemberLayout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jLabel14)
                    .addContainerGap(758, Short.MAX_VALUE)))
        );

        jpaddmemberLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfmname, tfmphone});

        jpaddmemberLayout.setVerticalGroup(
            jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaddmemberLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfmphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(52, 52, 52)
                .addComponent(jlpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaddmemberLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpaddmemberLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfmptamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(jpaddmemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpaddmemberLayout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );

        jpaddmemberLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlpdate, tfmname, tfmphone});

        tab.addTab("Add New Service", jpaddmember);

        jButton1.setText("       Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        searchfield.setText("Enter Name to Search");
        searchfield.setToolTipText("Search Members");
        searchfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchfieldMouseClicked(evt);
            }
        });
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        searchfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpallLayout = new javax.swing.GroupLayout(jpall);
        jpall.setLayout(jpallLayout);
        jpallLayout.setHorizontalGroup(
            jpallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
            .addGroup(jpallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpallLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(search_label)
                        .addGap(247, 247, 247))
                    .addGroup(jpallLayout.createSequentialGroup()
                        .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpallLayout.setVerticalGroup(
            jpallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpallLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jpallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(search_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab)
                .addGap(22, 22, 22))
        );

        jp1.add(jpall, "card6");

        jLabel19.setText("Your Security Question");

        ftf_secq.setEditable(false);

        ftf_seca.setText("Answer");
        ftf_seca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftf_secaMouseClicked(evt);
            }
        });
        ftf_seca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftf_secaActionPerformed(evt);
            }
        });
        ftf_seca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftf_secaKeyReleased(evt);
            }
        });

        jLabel34.setText("Answer the above question");

        fbresetpass.setText("Reset My Password");
        fbresetpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbresetpassActionPerformed(evt);
            }
        });

        flabel_newpass.setText("Your New Password");

        fpf_confpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpf_confpassActionPerformed(evt);
            }
        });
        fpf_confpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fpf_confpassKeyReleased(evt);
            }
        });

        flabel_confpass.setText("Confirm Your Password");

        fbsetpass.setText("Set Password");
        fbsetpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbsetpassActionPerformed(evt);
            }
        });

        jButton16.setText("         Back");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpforgotpasswordLayout = new javax.swing.GroupLayout(jpforgotpassword);
        jpforgotpassword.setLayout(jpforgotpasswordLayout);
        jpforgotpasswordLayout.setHorizontalGroup(
            jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpforgotpasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpforgotpasswordLayout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flabel_newpass)
                    .addGroup(jpforgotpasswordLayout.createSequentialGroup()
                        .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fbsetpass)
                            .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jpforgotpasswordLayout.createSequentialGroup()
                                    .addComponent(flabel_confpass)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fpf_confpass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpforgotpasswordLayout.createSequentialGroup()
                                    .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel34))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                    .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ftf_seca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ftf_secq, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fpf_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fbresetpass)))))
                        .addGap(59, 59, 59)
                        .addComponent(conf_pass1)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jpforgotpasswordLayout.setVerticalGroup(
            jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpforgotpasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpforgotpasswordLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftf_seca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)))
                    .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftf_secq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fbresetpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flabel_newpass)
                    .addComponent(fpf_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jpforgotpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flabel_confpass)
                    .addComponent(fpf_confpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conf_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(fbsetpass)
                .addGap(74, 74, 74))
        );

        jp1.add(jpforgotpassword, "card8");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Settings");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Account Settings");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (loggedin) {

            jp1.setVisible(true);
            jpall.setVisible(true);

            tab.setSelectedIndex(4);
            if (jphome.isVisible()) {
                jphome.setVisible(false);
            } else if (jpFAQS1.isVisible()) {
                jpFAQS1.setVisible(false);
            } else if (jpabout.isVisible()) {
                jpabout.setVisible(false);
            } else if (jpthemes.isVisible()) {
                jpthemes.setVisible(false);
            }

        } else {
            JOptionPane.showMessageDialog(null, "You are not logged in.");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        /*if (cpanel != null) {
            cpanel.setVisible(false);
        } else {
            jphome.setVisible(false);

        }
        jpabout.setVisible(true);*/
        if (jp1.isVisible()) {
            jp1.setVisible(false);
        } else if (jpFAQS1.isVisible()) {
            jpFAQS1.setVisible(false);
        } else if (jpthemes.isVisible()) {
            jpthemes.setVisible(false);
        }
        jpabout.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void tfunameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfunameMouseClicked
        // TODO add your handling code here:
        cleartext(tfuname, "Name");
    }//GEN-LAST:event_tfunameMouseClicked

    private void tfunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfunameActionPerformed
        // TODO add your handling code here:
        cleartext(tfuname, "Name");
    }//GEN-LAST:event_tfunameActionPerformed

    private void tfgymnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfgymnameMouseClicked
        // TODO add your handling code here:
        cleartext(tfgymname, "Gym Name");
    }//GEN-LAST:event_tfgymnameMouseClicked

    private void tfgymnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgymnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgymnameActionPerformed

    private void tfgymnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfgymnameKeyReleased
        // TODO add your handling code here:
        cleartext(tfgymname, "Gym Name");
    }//GEN-LAST:event_tfgymnameKeyReleased

    private void bregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregisterActionPerformed
        // TODO add your handling code here:

        signingup = true;
        if (password_confirm()) {
            String sql = "insert into gym (gname,guname,gpassword,gsecurityq,gsecuritya,settingscount) "
            + "values(?,?,?,?,?,?)";
            boolean registered = false;
            try {
                String confpassword;
                conn.setAutoCommit(false);

                gymname = tfgymname.getText().toLowerCase();

                user = tfuname.getText().toLowerCase();
                password = new String(pf.getPassword());
                System.out.println(password);
                confpassword = new String(pfconf.getPassword());
                System.out.println(confpassword);
                security_q = security_question.getSelectedIndex();
                security_ans = tfanswer.getText();
                if (!"your gymn name".equals(gymname) && gymname.length() != 0) {
                    if (!"your name".equals(user) && user.length() != 0) {
                        if (password.length() >= 8 && password.equals(confpassword)) {
                            if (!security_ans.equals("your answer") && security_ans.length() != 0) {
                                pst = conn.prepareStatement(sql);
                                pst.setString(1, gymname);
                                pst.setString(2, user);
                                pst.setString(3, password);
                                pst.setInt(4, security_q);
                                pst.setString(5, security_ans);
                                pst.setInt(6, 2);
                                int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to register"
                                    + " with the following Credentials!?");
                                if (ans == JOptionPane.YES_OPTION) {
                                    pst.executeUpdate();
                                    JOptionPane.showMessageDialog(null, user + " your " + gymname + " is successfully registered"
                                        + "\n username : " + user + "\n password : " + password, "Registered!!", JOptionPane.PLAIN_MESSAGE);

                                    registered = true;
                                    jpsignup.setVisible(false);
                                    jplogin.setVisible(true);

                                    conn.commit();
                                }

                            }
                        }
                    }
                }

            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, se + "\n db deleted restore if you have a copy", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!registered) {
                JOptionPane.showMessageDialog(null, "Please enter all the approriate details.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_bregisterActionPerformed

    private void pfconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfconfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfconfActionPerformed

    private void pfconfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfconfKeyReleased
        try {
            // TODO add your handling code here:
            String pass = pfconf.getText();

            if (pass.length() > 0 && pass.equals(pf.getText())) {

                load_img("right.png", confirm_pass);

            } else {
                load_img("wrong.png", confirm_pass);
            }
        } catch (IOException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pfconfKeyReleased

    private void pfconfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfconfKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_pfconfKeyTyped

    private void tfanswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfanswerMouseClicked
        // TODO add your handling code here:
        cleartext(tfanswer, "Your Answer");
    }//GEN-LAST:event_tfanswerMouseClicked

    private void tfanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfanswerActionPerformed

    private void tfanswerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfanswerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfanswerKeyPressed

    private void tfanswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfanswerKeyReleased
        // TODO add your handling code here:

        perform_action(bregister, evt);
    }//GEN-LAST:event_tfanswerKeyReleased

    private void pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pfActionPerformed

    private void tflusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tflusernameMouseClicked
        // TODO add your handling code here:
        cleartext(tflusername, "Username");
    }//GEN-LAST:event_tflusernameMouseClicked

    private void tflusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflusernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tflusernameActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (trial_expired()) {
            return;
        }
        jplogin.setVisible(false);
        jpforgotpassword.setVisible(true);
        forgot_setvisibility(false);
        ftf_seca.setText("");
        ftf_secq.setText(security_question.getItemAt(security_q).toString());

    }//GEN-LAST:event_jLabel3MouseClicked

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        // TODO add your handling code here:

        usere = tflusername.getText().toLowerCase();
        passworde = new String(pfl.getPassword());

        String sql = "Select * "
        + "from Gym  "
        + "where guname =? and gpassword=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, usere);
            pst.setString(2, passworde);
            rs = pst.executeQuery();

            if (rs.next()) {

                //uncomment for deployment
                /* if (trial_expired()) {//check for trial period only if uname and password are right, else rs = null
                    return;
                }*/
                jplogin.setVisible(false);
                //jploggedin.setVisible(true);//trying with jpall

                loggedin = true;
                security_q = rs.getInt("gsecurityq");
                tflusername.setText("Username");
                monthly_amount = rs.getDouble("Months_amt");
                for_month = rs.getInt("For_month");
                pfl.setText("");
                hidefields();
                update_trialperiod();
                /* usere=rs.getString("guname");
                passworde=rs.getString("gpassword");
                System.out.println("username="+usere+"\npassword="+passworde);*/
                jpall.setVisible(true);
                Display_mymembers();
                display_search(true);
            } else {
                JOptionPane.showMessageDialog(null, "The Username/Password is incorrect.",
                    "Invalid Username/Password.", JOptionPane.ERROR_MESSAGE);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + "The Username/Password is incorrect.", "Invalid Username/Password.", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bloginActionPerformed

    private void pflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pflActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pflActionPerformed

    private void pflKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pflKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            blogin.doClick();

        }
    }//GEN-LAST:event_pflKeyReleased

    private void table_mymemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mymemberMouseClicked
        // TODO add your handling code here:
        display_memberfields();
        table_mymember.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_table_mymemberMouseClicked

    private void table_mymemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mymemberMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_table_mymemberMouseEntered

    private void table_mymemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_mymemberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_mymemberKeyPressed

    private void table_mymemberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_mymemberKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {

            display_memberfields();
            table_mymember.setDefaultEditor(Object.class, null);
        } else {//if it is some other char other than up and down arrow, use the character to set the selected row having that char
            char ch = evt.getKeyChar();
            System.out.println("pressed char = \t" + ch);
            if (Character.isAlphabetic(ch)) {
                setrowselected(ch, table_mymember);
            }
        }
    }//GEN-LAST:event_table_mymemberKeyReleased

    private void tfdamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdamtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdamtActionPerformed

    private void tfdcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdcontactActionPerformed

    private void tfdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdnameActionPerformed

    private void tfddojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfddojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfddojActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (table_mymember.isCellSelected(table_mymember.getSelectedRow(), table_mymember.getSelectedColumn())) {
            if (password_confirm()) {
                String mid = table_mymember.getValueAt(table_mymember.getSelectedRow(), 0).toString();
                delete_record(mid);
            }
        } else {
            JOptionPane.showMessageDialog(null, "please select a member from the table to delete/remove from the gym.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (table_mymember.isCellSelected(table_mymember.getSelectedRow(), table_mymember.getSelectedColumn())) {
            load_updatefields();
            update_setvisible(true);
            //  JOptionPane.showMessageDialog(this,"Succesfully Updated.");

        } else {
            JOptionPane.showMessageDialog(null, "Select a Member from the table whose details are to be updated.");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void table_mymember1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mymember1MouseClicked

        show_payementfields();
    }//GEN-LAST:event_table_mymember1MouseClicked

    private void table_mymember1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mymember1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_table_mymember1MouseEntered

    private void table_mymember1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_mymember1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_mymember1KeyPressed

    private void table_mymember1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_mymember1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            show_payementfields();
        } else {//if it is some other char other than up and down arrow, use the character to set the selected row having that char
            char ch = evt.getKeyChar();
            System.out.println("pressed char = \t" + ch);
            if (Character.isAlphabetic(ch)) {
                setrowselected(ch, table_mymember1);
            }
        }
    }//GEN-LAST:event_table_mymember1KeyReleased

    private void tfdamt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdamt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdamt1ActionPerformed

    private void tfdcontact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdcontact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdcontact1ActionPerformed

    private void tfdname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdname1ActionPerformed

    private void tfddoj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfddoj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfddoj1ActionPerformed

    private void bamountpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bamountpaidActionPerformed
        // TODO add your handling code here:
        String slno;
        int op = JOptionPane.showConfirmDialog(null, tfdname1.getText() + " has Paid " + tfdamt1.getText() + "  ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            if (password_confirm()) {

                slno = table_mymember1.getValueAt(table_mymember1.getSelectedRow(), 0).toString();
                System.out.println(slno);
                System.out.println(hm.containsKey(Integer.parseInt(slno)));
                if (hm.containsKey(Integer.parseInt(slno))) {
                    try {
                        String mid = hm.get((Integer.parseInt(slno))).toString();
                        update_payements(Integer.parseInt(mid), "Yes");
                        update_lastpdate(mid);
                        JOptionPane.showMessageDialog(null, "Successfully Updated");
                        flush_rows(table_mymember1);
                        hm.clear();
                        no_payee = 0;
                        Display_payementinfo();
                        update_for_month();
                        update_monthly_amount(Double.parseDouble(tfdamt1.getText()));
                        flush_fields();
                    } catch (SQLException ex) {
                        Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    System.out.println(hm);
                }
            }

        }

    }//GEN-LAST:event_bamountpaidActionPerformed

    private void stf_amountrcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stf_amountrcvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stf_amountrcvActionPerformed

    private void stf_amountbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stf_amountbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stf_amountbalActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        // TODO add your handling code here:
        int index = tab.getSelectedIndex();
        switch (index) {
            case 0:
            Display_mymembers();
            display_search(true);
            break;
            case 1:
            updatingdp = false;// adding member so load_image effects there
            display_search(false);
            if (jchmexisting.isSelected()) {
                setvisible_existing(true);
            } else {
                setvisible_existing(false);
            }
            break;
            case 2:
            payinfo = true;
            Display_payementinfo();
            display_search(true);
            break;
            case 3:
            display_search(false);
            show_stats();
            break;
            case 4:
            display_search(false);
            if (firstclick) {
                setdetails();
                hidefields();

                firstclick = false;
            }

        }
    }//GEN-LAST:event_tabMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchfieldMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_searchfieldMouseClicked

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldActionPerformed

    private void searchfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfieldKeyReleased
        // TODO add your handling code here:
        String entered = null, name;
        JTable table;
        if (tab.isEnabledAt(0)) {
            table = table_mymember;
        } else {
            table = table_mymember1;
        }

        entered = searchfield.getText().trim().toLowerCase();
        int c = 0;
        for (int i = s_row; c < table.getRowCount(); c++, i = (i + 1) % table.getRowCount()) {
            name = table.getValueAt(i, 1).toString();
            System.out.println("String processing:  " + entered);
            if (name.startsWith(entered)) {
                table.setRowSelectionInterval(i, i);
                s_row = (i + 1) % table.getRowCount();
                display_memberfields();
                break;

            } else if (name.contains(entered)) {
                table.setRowSelectionInterval(i, i);
                s_row = (i + 1) % table.getRowCount();
                display_memberfields();
                break;
            }

        }

    }//GEN-LAST:event_searchfieldKeyReleased

    private void searchfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfieldKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_searchfieldKeyTyped

    private void ftf_secaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftf_secaMouseClicked
        // TODO add your handling code here:
        cleartext(ftf_seca, "Answer");
    }//GEN-LAST:event_ftf_secaMouseClicked

    private void ftf_secaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftf_secaActionPerformed
        // TODO add your handling code here:
        cleartext(ftf_seca, "Answer");
    }//GEN-LAST:event_ftf_secaActionPerformed

    private void ftf_secaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftf_secaKeyReleased
        // TODO add your handling code here:
        perform_action(fbresetpass, evt);
    }//GEN-LAST:event_ftf_secaKeyReleased

    private void fbresetpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbresetpassActionPerformed
        // TODO add your handling code here:
        if (ftf_seca.getText().equalsIgnoreCase(security_ans)) {
            forgot_setvisibility(true);
        } else {
            JOptionPane.showMessageDialog(null, "Answer to your security question is invalid.", "Invalid", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_fbresetpassActionPerformed

    private void fpf_confpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpf_confpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpf_confpassActionPerformed

    private void fpf_confpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fpf_confpassKeyReleased
        // TODO add your handling code here:
        perform_action(fbsetpass, evt);
        try {
            // TODO add your handling code here:
            String pass = fpf_confpass.getText();

            if (pass.length() > 0 && pass.equals(fpf_newpass.getText())) {

                load_img("right.png", conf_pass1);

            } else {
                load_img("wrong.png", conf_pass1);
            }
        } catch (IOException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fpf_confpassKeyReleased

    private void fbsetpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbsetpassActionPerformed
        // TODO add your handling code here:

        if (fpf_newpass.getText().length() >= 8) {
            if (fpf_newpass.getText().equals(fpf_confpass.getText())) {
                passworde = fpf_newpass.getText();
                update_password();
                JOptionPane.showMessageDialog(null, "your Password is Reset to:" + passworde);
                jpforgotpassword.setVisible(false);
                jplogin.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "The passwords dont Match.\n Retype the Password");
            }
        } else {
            JOptionPane.showMessageDialog(null, "The password must be atleast 8 characters");
        }
    }//GEN-LAST:event_fbsetpassActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        jpforgotpassword.setVisible(false);
        jplogin.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void tfmptamtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmptamtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tfmptamtKeyTyped

    private void tfmptamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmptamtActionPerformed

    }//GEN-LAST:event_tfmptamtActionPerformed

    private void tfmptamtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfmptamtMouseClicked
        // TODO add your handling code here:
        cleartext(tfmptamt, "Amt");
    }//GEN-LAST:event_tfmptamtMouseClicked

    private void tfmphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmphoneKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_tfmphoneKeyTyped

    private void tfmphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmphoneActionPerformed

    private void tfmphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfmphoneMouseClicked
        // TODO add your handling code here:
        cleartext(tfmphone, "Number");
    }//GEN-LAST:event_tfmphoneMouseClicked

    private void tfmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmnameActionPerformed
        // TODO add your handling code here:
        cleartext(tfmname, "Full Name");
    }//GEN-LAST:event_tfmnameActionPerformed

    private void tfmnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfmnameMouseClicked
        // TODO add your handling code here:
        cleartext(tfmname, "Full Name");
    }//GEN-LAST:event_tfmnameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cellfixx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cellfixx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cellfixx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cellfixx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cellfixx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bamountpaid;
    private javax.swing.JButton blogin;
    private javax.swing.JButton bregister;
    private javax.swing.JLabel conf_pass1;
    private javax.swing.JLabel confirm_pass;
    private javax.swing.JLabel confirm_pass1;
    private javax.swing.JButton fbresetpass;
    private javax.swing.JButton fbsetpass;
    private javax.swing.JLabel flabel_confpass;
    private javax.swing.JLabel flabel_newpass;
    private javax.swing.JPasswordField fpf_confpass;
    private javax.swing.JPasswordField fpf_newpass;
    private javax.swing.JTextField ftf_seca;
    private javax.swing.JTextField ftf_secq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlans;
    private javax.swing.JLabel jlconfpass;
    private javax.swing.JLabel jlgymname;
    private javax.swing.JLabel jlpass;
    private com.toedter.calendar.JDateChooser jlpdate;
    private javax.swing.JLabel jlquest;
    private javax.swing.JLabel jluname;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jpaddmember;
    private javax.swing.JPanel jpall;
    private javax.swing.JPanel jpforgotpassword;
    private javax.swing.JPanel jplogin;
    private javax.swing.JPanel jpmembers;
    private javax.swing.JPanel jppayinfo;
    private javax.swing.JPanel jpsettings;
    private javax.swing.JPanel jpsignup;
    private javax.swing.JPanel jpstats;
    private javax.swing.JPasswordField pf;
    private javax.swing.JPasswordField pfconf;
    private javax.swing.JPasswordField pfl;
    private javax.swing.JLabel search_label;
    private javax.swing.JTextField searchfield;
    private javax.swing.JComboBox security_question;
    private javax.swing.JTextField stf_amountbal;
    private javax.swing.JTextField stf_amountrcv;
    private javax.swing.JTextField stf_females;
    private javax.swing.JTextField stf_males;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable table_mymember;
    private javax.swing.JTable table_mymember1;
    private javax.swing.JTextField tfanswer;
    private javax.swing.JTextField tfdamt;
    private javax.swing.JTextField tfdamt1;
    private javax.swing.JTextField tfdcontact;
    private javax.swing.JTextField tfdcontact1;
    private javax.swing.JTextField tfddoj;
    private javax.swing.JTextField tfddoj1;
    private javax.swing.JTextField tfdname;
    private javax.swing.JTextField tfdname1;
    private javax.swing.JTextField tfgymname;
    private javax.swing.JTextField tflusername;
    private javax.swing.JTextField tfmname;
    private javax.swing.JTextField tfmphone;
    private javax.swing.JTextField tfmptamt;
    private javax.swing.JTextField tfuname;
    // End of variables declaration//GEN-END:variables
}
